// <auto-generated />
namespace Canaro_Trello.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Updateusertable2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateusertable2));
        
        string IMigrationMetadata.Id
        {
            get { return "202104272024247_Update user table - 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
