// <auto-generated />
namespace Canaro_Trello.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class stringguids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stringguids));
        
        string IMigrationMetadata.Id
        {
            get { return "202105121639404_string guids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
