// <auto-generated />
namespace Canaro_Trello.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addrolestousertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addrolestousertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202104281945049_Add roles to user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
